name       : libabw
version    : 0.1.3
release    : 3
source     :
    - https://dev-www.libreoffice.org/src/libabw/libabw-0.1.3.tar.xz : e763a9dc21c3d2667402d66e202e3f8ef4db51b34b79ef41f56cacb86dcd6eed
license    : MPL-2.0
component  : programming
summary    : Library for parsing abiword documents
description: |
    Library for parsing abiword documents.
builddeps  :
    - pkgconfig(librevenge-0.0)
    - gperf
    - libboost-devel
setup      : |
    %patch -p1 < $pkgfiles/boost-fix.patch
    %configure
build      : |
    %make
install    : |
    %make_install
